# Generated by Django 5.0.2 on 2024-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='create',
        ),
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(),
        ),
    ]
